# Generated by Django 4.2.7 on 2026-03-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], max_length=10)),
                ('scan_status', models.CharField(choices=[('served', 'Served'), ('denied', 'Denied'), ('duplicate', 'Duplicate')], max_length=10)),
                ('scanned_barcode', models.CharField(max_length=50)),
                ('scan_date', models.DateField()),
                ('scan_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to='accommodation.student')),
            ],
            options={
                'db_table': 'meal_register',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'meal_type', 'scan_date'], name='meal_regist_student_f3a6a8_idx'), models.Index(fields=['scan_date'], name='meal_regist_scan_da_cd35ec_idx')],
            },
        ),
    ]
