# Generated by Django 4.2.7 on 2026-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='available_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
