# Generated by Django 4.2.7 on 2026-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_hostel_available_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
