# Generated by Django 4.2.7 on 2026-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_hostel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationapplication',
            name='floor_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='floor_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
