# Generated by Django 4.2.7 on 2026-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_floor_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_src',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='work_for_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
