# Generated by Django 4.2.7 on 2026-05-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_student_date_of_birth_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationapplication',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accommodation.room'),
        ),
    ]
