# Generated by Django 4.2.7 on 2026-03-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_barcode', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200)),
                ('log_date', models.DateField()),
                ('log_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to='accommodation.student')),
            ],
            options={
                'db_table': 'gate_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_date'], name='gate_log_log_dat_e32921_idx'), models.Index(fields=['student', 'log_date'], name='gate_log_student_76223b_idx')],
            },
        ),
    ]
